version: "3.7"
services:

  cti_receiver:
    build:
      context: .
    container_name: cti_receiver
    environment:
      - BROKER_HOST=127.0.0.1
      - BROKER_PORT=5672
      - BROKER_USER=
      - BROKER_PASSWORD=
      - MONGO_HOST=127.0.0.1
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASSWORD=
    restart: always